package log

import (
	"fmt"
	"io"
	"log"
	"os"
	"runtime"
	"strings"
	"sync"
)

// These flags define which text to prefix to each log entry generated by the Logger.
const (
	// Bits or'ed together to control what's printed. There is no control over the
	// order they appear (the order listed here) or the format they present (as
	// described in the comments).  A colon appears after these items:
	//	[log] 2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
	Ldate         = log.Ldate                             // the date: 2009/01/23
	Ltime         = log.Ltime                             // the time: 01:23:23
	Lmicroseconds = log.Lmicroseconds                     // microsecond resolution: 01:23:23.123123.  assumes Ltime.
	Llongfile     = log.Llongfile                         // full file name and line number: /a/b/c/d.go:23
	Lshortfile    = log.Lshortfile                        // final file name element and line number: d.go:23. overrides Llongfile
	Lpackage      = log.Lshortfile << 1                   // package name: [log]
	LstdFlags     = log.LstdFlags | Lshortfile | Lpackage // initial values for the standard logger
)

//日志级别
const (
	LEVEL_DISABLE = 0 //关闭日志功能
	LEVEL_DEBUG   = 1 << iota
	LEVEL_INFO
	LEVEL_WARN
	LEVEL_ERROR
	LEVEL_CRITICAL
	LEVEL_PANIC
	LEVEL_FATAL
	LEVEL_ALL = LEVEL_DEBUG | LEVEL_INFO | LEVEL_WARN | LEVEL_ERROR | LEVEL_CRITICAL | LEVEL_PANIC | LEVEL_FATAL

	//默认日志级别为
	LEVEL_DEFAULT = LEVEL_INFO
)

var (
	LevelText = map[string]int{
		"disable":  LEVEL_DISABLE,
		"debug":    LEVEL_DEBUG,
		"info":     LEVEL_INFO,
		"warn":     LEVEL_WARN,
		"error":    LEVEL_ERROR,
		"critical": LEVEL_CRITICAL,
		"panic":    LEVEL_PANIC,
		"fatal":    LEVEL_FATAL,
		"all":      LEVEL_ALL,
	}

	logPrefixs = map[int]string{
		LEVEL_DEBUG:    "[DEBUG]",
		LEVEL_INFO:     "[INFO]",
		LEVEL_WARN:     "[WARN]",
		LEVEL_ERROR:    "[ERROR]",
		LEVEL_CRITICAL: "[CRITICAL]",
		LEVEL_PANIC:    "[PANIC]",
		LEVEL_FATAL:    "[FATAL]",
	}
)

type Logger struct {
	*log.Logger
	mu    sync.Mutex
	level int
}

func packageOf(file string) string {
	pos := strings.LastIndex(file, "/")
	if pos != -1 {
		pos1 := strings.LastIndex(file[:pos], "/src/")
		if pos1 != -1 {
			return file[pos1+5 : pos]
		}
	}
	return "UNKNOWN"
}

func New(out io.Writer, prefix string, flag int) *Logger {
	return &Logger{
		log.Logger: log.New(out, prefix, flag),
		level:      LEVEL_DEFAULT,
	}
}

func (l *Logger) SetOutput(w io.Writer) {
	l.mu.Lock()
	prefix := l.Prefix()
	flags := l.Flags()
	levels := l.Levels()
	l.mu.Unlock()
	*l = Logger{
		log.Logger: log.New(w, prefix, flags),
		level:      levels,
	}
}

func (l *Logger) SetLevel(level int) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.level = level
}

func (l *Logger) Levels() int {
	return l.level
}

func (l *Logger) Output(calldepth int, s string) error {
	if Lpackage&l.level != 0 {
		if _, file, _, ok := runtime.Caller(calldepth); ok {
			l.SetPrefix(l.Prefix() + "[" + packageOf(file) + "] ")
		}
	}

	//再加1层，是因为l.loger调用
	calldepth = calldepth + 1
	return l.Logger.Output(calldepth, s)
}

func (l *Logger) Print(v ...interface{}) {
	//又包了2层
	localCalldepth := 2 + 2
	l.Output(localCalldepth, fmt.Sprint(v...))
}

func (l *Logger) Println(v ...interface{}) {
	//又包了2层
	localCalldepth := 2 + 2
	l.Output(localCalldepth, fmt.Sprintln(v...))
}

func (l *Logger) Printf(format string, v ...interface{}) {
	//又包了2层
	localCalldepth := 2 + 2
	l.Output(localCalldepth, fmt.Sprintf(format, v...))
}

func (l *Logger) Panic(v ...interface{}) {
	if LEVEL_PANIC&l.level == 0 {
		return
	}

	l.SetPrefix(logPrefixs[LEVEL_PANIC] + " ")
	s := fmt.Sprint(v...)
	//又包了1层
	localCalldepth := 2 + 1
	l.Output(localCalldepth, s)
	panic(s)
}

func (l *Logger) Panicln(v ...interface{}) {
	if LEVEL_PANIC&l.level == 0 {
		return
	}

	l.SetPrefix(logPrefixs[LEVEL_PANIC] + " ")
	s := fmt.Sprintln(v...)
	//又包了1层
	localCalldepth := 2 + 1
	l.Output(localCalldepth, s)
	panic(s)
}

func (l *Logger) Panicf(format string, v ...interface{}) {
	if LEVEL_PANIC&l.level == 0 {
		return
	}

	l.SetPrefix(logPrefixs[LEVEL_PANIC] + " ")
	s := fmt.Sprintf(format, v...)
	//又包了1层
	localCalldepth := 2 + 1
	l.Output(localCalldepth, s)
	panic(s)
}

func (l *Logger) Fatal(v ...interface{}) {
	if LEVEL_FATAL&l.level == 0 {
		return
	}

	l.SetPrefix(logPrefixs[LEVEL_FATAL] + " ")
	l.Print(v...)
	os.Exit(1)
}

func (l *Logger) Fatalln(v ...interface{}) {
	if LEVEL_FATAL&l.level == 0 {
		return
	}

	l.SetPrefix(logPrefixs[LEVEL_FATAL] + " ")
	l.Println(v...)
	os.Exit(1)
}

func (l *Logger) Fatalf(format string, v ...interface{}) {
	if LEVEL_FATAL&l.level == 0 {
		return
	}

	l.SetPrefix(logPrefixs[LEVEL_FATAL] + " ")
	l.Printf(format, v...)
	os.Exit(1)
}
